name: R-CMD-check
  on:
  push:
  branches: [ main ]
  pull_request:
  branches: [ main ]

  jobs:
  R-CMD-check:
  runs-on: ubuntu-latest
  timeout-minutes: 30
  steps:
  - uses: actions/checkout@v4

        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 'release'
            use-public-rspm: true

        - uses: r-lib/actions/setup-pandoc@v2

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check

        - name: R CMD check (skip vignettes/manual)
          run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual','--ignore-vignettes'), error_on = 'error')"